# Generated by Django 2.1 on 2018-08-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0002_auto_20180803_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Max',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date performed')),
                ('max_lift', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_tracker.Exercise')),
            ],
        ),
        migrations.DeleteModel(
            name='maxTracker',
        ),
    ]
